game_management/urls.py
from django.conf.urls import url

from game_management.views import ChoiceView, save_move, WinnerView

urlpatterns = [
    url(r'^playing-game/(?P<pk>\d+)/$', ChoiceView.as_view(),
        name='load_game'),
    url(r'^win-view/$', WinnerView.as_view(), name='winner_view'),
    url(r'^next-step/$', save_move, name='next_game_step'),
]

rpsgame/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from game_management.views import StartGameView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', StartGameView.as_view(), name='start_game'),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^game-management/', include('game_management.urls',
                                      namespace='game_management')),
]

user/urls.py
urlpatterns = [
]

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}RPS Game{% endblock %}</title>
    <link href="{% static 'css/rps_game_styles.css' %}" rel="stylesheet" />
</head>
<body>
    <div id="board_div">
        <h1>RPS GAME</h1>
                {% block forms_block %}
                    <div class="primary_form">
                        <h3>Enter Player's Name</h3>
                        <form id='start_game_form' method="post">
                            {% csrf_token %}
                            {{ form }}
                            <input type="submit" value="Start">
                        </form>
                    </div>
                {% endblock forms_block %}


                <div class="score_div">
                    {% block score %}{% endblock score %}
                </div>

        {% block image  %}
            <img src="{% static 'img/rps_3.gif' %}">
        {% endblock image %}
        {% block winner_block  %} {% endblock winner_block %}
    </div>
</body>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous">
</script>

{% block javascript %}{% endblock %}
</html>

templates/playing_screen.html
{% extends 'index.html' %}

{% load staticfiles %}

{% block page_title %} Playing {% endblock %}

{% block forms_block %}

    <div class="form_div">
        <form id='start_game_form' method="post">
            {% csrf_token %}
            <div>
                <h1>Round <span id="round_number">{{ actual_round }}</span></h1>
            </div>
            <div id="player1_name"><h2>{{ player_1 }}</h2></div>
            <div id="player2_name" style="display: none"><h2>{{ player_2 }}</h2></div>
            {{ form.player_choice }}
            <div id="player1_button">
                <input id="ok_player_1" class="game-button" type="button" value="Ok">
            </div>
            <div id="player2_button" style="display: none">
                <input id="ok_player_2" class="game-button" type="button" value="Ok">
            </div>
        </form>
    </div>
{% endblock %}

{% block score %}
    <h3>Score</h3>
    <div>Round - Winner</div>
    <div>
        <ul id="score_list">
            {% for winner in score %}
                <li> - {{ winner }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}


{% block image  %}
    <img src="{% static 'img/rps_1.gif' %}" style="width: 500px">
{% endblock image %}

{% block javascript %}
    <script>
        var game = {{ game }};
        var url_game_winner = "{% url 'game_management:winner_view' %}";
        var url = "{% url 'game_management:next_game_step' %}";
        var token = '{{ csrf_token }}';
    </script>
    <script src="{% static 'js/game_behaviour.js' %}"></script>
{% endblock %}

templates/winner_screen.html
{% extends "index.html" %}

{% load staticfiles %}

{% block page_title %} Game Over {% endblock %}

{% block  forms_block %}{% endblock %}

{% block image  %}
    <img src="{% static 'img/rps_2.gif' %}" style="width: 50%; height: 50%!important;">
{% endblock image %}

{% block  winner_block %}
    <h1>We Have a WINNER!!</h1>
    <h1>{{ winner }} is the new EMPEROR!</h1>
    <input class="game-button" type="button" onclick="window.location='{% url 'start_game' %}'" value="Play Again">
{% endblock winner_block %}